site_name: "IIEST Wiki"
site_description: "A comprehensive knowledge base for study materials, AMAs, and placement statistics"
site_author: "Campus Community"
site_url: "https://wiki.0xiiest.org"

nav:
  - Home: index.md
  # - Study Materials:
  #     - Courses:
  #         - Computer Science: study/cs/index.md
  #         - Mathematics: study/math/index.md
  #         - Physics: study/physics/index.md
  #         - Past Papers: study/past-papers.md
  #         - Lecture Slides: study/lecture-slides.md
  - Admission:
      - UG: admission/ug.md
  - Placement Statistics:
      - 2025: placements/2025.md
  - AMAs:
      - 2025:
          - Coming Soon: amas/2025-demo.md
  - Contacts: contacts.md

theme:
  name: "material"
  # logo: "assets/images/logo.png"
  favicon: "assets/images/logo.png"
  language: "en"
  palette:
    - scheme: default
      primary: "white"
      accent: "indigo"
      toggle:
        icon: "material/brightness-7"
        name: "Switch to dark mode"
    - scheme: slate
      primary: "black"
      accent: "indigo"
      toggle:
        icon: "material/brightness-4"
        name: "Switch to light mode"
  font:
    text: "Inter"
    code: "Roboto Mono"
  features:
    - navigation.instant
    # - navigation.tabs
    # - toc.integrate
    - content.code.annotate

plugins:
  - search:
      separator: '[\s\-]+'
  - charts:

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

extra_css:
  - assets/css/custom.css

use_directory_urls: false

repo_url: https://github.com/0xIIEST/wiki